### PR TITLE
Correct the logo

### LINKED ISSUE #10: Correct the logo
Now it is pretty compressed

### PR DESCRIPTION
**Pull request by markelog**
Fixes #10

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
:+1:

**Comment by mdevils** [comment]
Previous version looked better on retina display

**Comment by markelog** [comment]
I have retina display, it seems proposed one is much better then the other

**Comment by mdevils** [comment]
LGTM

**Comment by mdevils** [comment]
Errrr, I opened it and it looks way worse now :(

**Comment by mdevils** [comment]
screen shot 2015-05-12 at 16 14 09

**Comment by markelog** [comment]
> Errrr, I opened it and it looks way worse now :(

Opened where? In what way?

**Pull request merged**
