### PR TITLE
Add version number to the homepage

### PR DESCRIPTION
**Pull request by hzoo**
screen shot 2015-12-10 at 4 29 37 pm

### CODE REVIEW

**Comment by markelog** [comment]
Can put it somewhere else? I fear it might be confusing for some people

**Comment by hzoo** [comment]
Yeah where would be a good place. We can also be more verbose and say like latest version is x

**Comment by markelog** [comment]
> We can also be more verbose and say like latest version is x

Yeah, my thoughts exactly, although i'm not sure on "where"

**Comment by hzoo** [comment]
Going to just do https://github.com/jscs-dev/node-jscs/commit/89b0440a21ec8253743918ebce57ab88017824ea instead then.

**Pull request closed without merging**
