### PR TITLE
Homepage: add jscs features (and pictures!)

### LINKED ISSUE #24: Show what JSCS does on home page (picture, gif)
Originally reported by the @hzoo in - https://github.com/jscs-dev/node-jscs/issues/1286

--
Also I think it would be nice to give an example of what jscs does in the about/home page. config/install info - So maybe an example .jscs config that shows off the common features (preset + extend) + autofix.

### PR DESCRIPTION
**Pull request by hzoo**
WIP/ideas @jscs-dev/core

Another idea might be to show a gif isntead of a picture (or maybe show the gif on hover if it makes sense like for autoconfigure, autofix, etc)? Ref/Fixes #24 

screencapture-localhost-3000-1442546041078

### CODE REVIEW

**Comment by hzoo** [comment]
@addyosmani Could we get your input on this? I wanted the homepage to showcase what jscs does (more visually) instead of just saying it's a style checker. Gifs could be cool too (and right now some of the pictures are just from the awesome blog post you did a while ago), so the pictures could probably be better/more creative.

**Comment by hzoo** [comment]
Anyone have feedback on this? We should do this soon

**Comment by mdevils** [comment]
I think this looks quite impressive :)

**Comment by mdevils** [comment]
I asked my friend designer to make this idea in more styled and beautiful way. She will work on it in 2 weeks approx.

**Comment by hzoo** [comment]
Ok great - basic idea is to showcase our main features through pictures/video. Or better we make it interactive but that's probably out of scope for this

**Comment by markelog** [comment]
> I asked my friend designer to make this idea in more styled and beautiful way. She will work on it in 2 weeks approx.

Tasha?

**Comment by mdevils** [comment]
@markelog Yes :)

**Comment by markelog** [comment]
I think we can land this while we wait :-)

**Comment by markelog** [comment]
How this would look like on mobile btw?

**Comment by mdevils** [comment]
@markelog I'm not sure, all the pics are different in resolution, colors and sizes.

**Comment by hzoo** [comment]
Ok so I'l redo the pictures and we can land this early version, and update later?

**Comment by markelog** [comment]
Sounds good to me

**Comment by mdevils** [comment]
Sounds also good to me

**Comment by hzoo** [comment]
Ok updated the op with the whole page. Used my own screenshots so it's the same color scheme.

**Comment by markelog** [comment]
Judging by the screenshot, pics are not homogenous, so i think we can land this with releasing 2.2

**Comment by hzoo** [comment]
Yeah they aren't all the same size - I didn't do any tinkering other than a bit of cropping

**Pull request merged**
