### PR TITLE
Added filtering to rules list

### PR DESCRIPTION
**Pull request by dutzi**

### CODE REVIEW

**Comment by markelog** [comment]
I guess user could always do the `ctrl+f` bit, but it seems interesting.

Anyway, would you mind adding reflection of search input to the url? So people could pass those search queries?

**Comment by markelog** [comment]
If you decided to do it, you might want to wait on #35 since it would be much easier to implement with the "standart" route module

**Comment by dutzi** [comment]
It's the first thing I was looking for when i encountered that page. I just like it when I can see all things related to _something_ ("spaces", "anonymous", etc...) without scrolling. 

I'm not too familiar with React, but sure I'll give it a shot.

**Comment by markelog** [comment]
#35 is merged, it seems we can proceed with this

**Comment by dutzi** [comment]
Done!

**Comment by markelog** [comment]
Hey, sorry for the hold up, it turns out there was an issue with react-router, we fixed that only just now, tried to land this, but there is conflict with current dev, could you check it out?

**Comment by dutzi** [comment]
np! merged it.

**Comment by markelog** [comment]
Hm, it seems there is some problem at the `npm run build` execution - 

``` bash
/Users/arkel/Workspace/jscs-dev.github.io/node_modules/vow/lib/vow.js:104
            throw e;
                  ^
Error: Invariant Violation: You cannot modify a static location
    at invariant (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react/lib/invariant.js:42:15)
    at StaticLocation.throwCannotModify (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react-router/lib/locations/StaticLocation.js:10:3)
    at Function.replaceWith (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react-router/lib/createRouter.js:236:18)
    at [object Object].componentWillMount (/Users/arkel/Workspace/jscs-dev.github.io/app/views/AppView/index.jsx:25:29)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react/lib/ReactCompositeComponent.js:228:14)
    at [object Object].wrapper [as mountComponent] (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at [object Object].wrapper [as mountComponent] (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/arkel/Workspace/jscs-dev.github.io/node_modules/react/lib/ReactReconciler.js:38:35)
```

**Comment by dutzi** [comment]
Fixed it in 8151a7e

**Pull request closed without merging**
