### PR TITLE
Correct the logo

### LINKED ISSUE #10: Correct the logo
Now it is pretty compressed

### PR DESCRIPTION
**Pull request by markelog**
Fixes #10 

Let's try this again

### CODE REVIEW

**Comment by markelog** [comment]
I will merge this for now, we can adjust it if needed later

**Comment by mdevils** [comment]
Yay, SVG

**Comment by markelog** [comment]
Two issues there, first, correct proportion for it should be 1.5 i.e. 150x100, don't have software to crop it. And second i included image to the html directly, is there a better way to included it in CSS?

**Comment by hzoo** [comment]
I guess we could use `background-image: url("logo.svg");` if you want to use css?

**Comment by markelog** [comment]
Need a correct loader to make it `data:image` style, like svg-loader

**Pull request closed without merging**
